### ISSUE TITLE
Does it support Tensorflow?

### ISSUE THREAD

**Issue by BobLiu20** [BaguaSys/bagua#153]
I see example only with PyTorch

**Comment by NOBLES5E** [comment]
Currently the bagua python package does not support tensorflow. There are some undergoing work happening [in `bagua-core`](https://github.com/BaguaSys/bagua-core/pull/32/files) so that tensorflow can use its C API for distributed learning, but it is created for internal scenarios and nowhere near complete.

**Comment by NOBLES5E** [comment]
Feel free to let me know if there are any other questions :)
